# This workflow tests a PyPI release by installing the corresponding package with `pip` and
# importing it with Python.

on:
  workflow_call:
    inputs:
      package_name:
        required: true
        type: string
        description: "Name of the PyPI package to test"
      version:
        required: true
        type: string
        description: "Version of the PyPI package to test"

jobs:
  test-pypi-release:
    name: Test PyPI release
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Set PyPI credentials in ~/.netrc
        uses: extractions/netrc@v1
        with:
          machine: pypi.arkhn.com
          username: ${{ secrets.PYPI_ARKHN_USERNAME }}
          password: ${{ secrets.PYPI_ARKHN_PASSWORD }}

      - name: Install package
        run: python -m pip install --index-url=https://pypi.arkhn.com/simple ${{ inputs.package_name }}==${{ inputs.version }}

      - name: Test package's import
        run: python -c "import ${{ inputs.package_name }}"
