# This workflow tests a Docker release by pulling the corresponding image.
#
# This workflow requires a `docker-compose.yml` file at the root of the repository, which should
# take into account the `VERSION` environment variable to pull the relevant image's version.

on:
  workflow_call:
    inputs:
      image_name:
        required: true
        type: string
        description: "Name of the Docker image to test"
      version:
        required: true
        type: string
        description: "Version of the Docker image to test"

jobs:
  test-docker-release:
    name: Test Docker release
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Login against a Docker registry
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_LOGIN }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Pull Docker image
        env:
          VERSION: ${{ inputs.version }}
        run: docker-compose pull ${{ inputs.image_name }}
